services:
  db-sd:
    image: postgis/postgis:16-3.4
    container_name: db-sd
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
        - "5432:5432"
    volumes:
      - .pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 12
  rabbitmq-sd:
    image: rabbitmq:3-management
    container_name: rabbitmq-sd
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  backend-sd:
    build:
      context: ..
      dockerfile: apps/backend/Dockerfile.dev
    container_name: backend-sd
    working_dir: /app/apps/backend
    command: >
      watchmedo auto-restart
      --directory=/app/apps/backend
      --pattern=*.py
      --recursive
      --
      python manage.py runserver 0.0.0.0:8971
    env_file:
      - ../apps/backend/.env
    environment:
      POSTGRES_HOST: db-sd
      POSTGRES_PORT: 5432
      WORKER_ID: 1
    depends_on:
      db-sd:
        condition: service_healthy
      rabbitmq-sd:
        condition: service_started
    ports:
      - "8971:8971"
    volumes:
      - ../apps/backend:/app/apps/backend

  celery-worker-sd-1:
    build:
      context: ..
      dockerfile: apps/backend/Dockerfile.dev
    container_name: celery-worker-sd-1
    working_dir: /app/apps/backend
    command: >
      watchmedo auto-restart
      --directory=/app/apps/backend
      --pattern=*.py
      --recursive
      --
      celery -A config worker -l info
    depends_on:
      backend-sd:
        condition: service_started
      rabbitmq-sd:
        condition: service_started
    env_file:
      - ../apps/backend/.env
    volumes:
      - ../apps/backend:/app/apps/backend


  celery-beat-sd:
    build:
      context: ..
      dockerfile: apps/backend/Dockerfile.dev
    container_name: celery-beat-sd
    working_dir: /app/apps/backend
    command: >
      watchmedo auto-restart
      --directory=/app/apps/backend
      --pattern=*.py
      --recursive
      --
      celery -A config beat -l info
    depends_on:
      backend-sd:
        condition: service_started
      rabbitmq-sd:
        condition: service_started
    env_file:
      - ../apps/backend/.env
    volumes:
      - ../apps/backend:/app/apps/backend


volumes:
  .pgdata:
